import { useState, useEffect, useMemo } from "react";
import {
  Sparkles,
  Check,
  X,
  ArrowRight,
  AlertTriangle,
  Camera,
  ChevronDown,
  ChevronUp,
  Clock,
  Wrench,
  Package,
  Zap,
  TrendingUp,
} from "lucide-react";
import clsx from "clsx";
import { toast } from "sonner";
import { Modal } from "@/components/ui/Modal";
import { applyAIEstimateLines, selectRO } from "@/lib/shop-store";
import { customers } from "@/data/customers";
import { vehicles } from "@/data/vehicles";
import { usd, usdCents } from "@/lib/format";

// ============================================================================
// Types
// ============================================================================

type Phase = "thinking" | "review" | "submitting" | "success";

type Confidence = "high" | "medium" | "low";

type Source = "shop-history" | "mitchell1" | "worldpac" | "oem" | "ai-inferred";

type ProposedLine = {
  id: string;
  // Finding side
  findingSeverity: "red" | "yellow";
  findingText: string;
  findingNotes?: string;
  hasPhoto: boolean;
  // Proposal side
  description: string;
  partNumber: string;
  partVendor: string;
  partPrice: number;
  laborHours: number;
  laborRate: number;
  // Trust signals
  confidence: Confidence;
  confidencePercent: number;
  sources: Source[];
  reasoning: string;
  similarJobs?: { roId: string; vehicle: string; date: string; hours: number }[];
};

// ============================================================================
// Hero-scenario proposed lines (RO 4847 — Med Trust MT-47)
// In production this is generated by the AI from inspection findings + vehicle
// history + parts catalogs. For the demo we hand-craft believable output.
// ============================================================================

const HERO_LINES: ProposedLine[] = [
  {
    id: "ai-1",
    findingSeverity: "red",
    findingText: "Front brake pads — metal-on-metal driver side, 2mm passenger",
    findingNotes: "Recommend pad replacement + rotor turn while apart",
    hasPhoto: true,
    description: "Front brake job — pad replacement + rotor resurface",
    partNumber: "WAG-MX1639",
    partVendor: "Worldpac",
    partPrice: 98.4,
    laborHours: 4.0,
    laborRate: 148,
    confidence: "high",
    confidencePercent: 95,
    sources: ["shop-history", "mitchell1", "worldpac"],
    reasoning:
      "Wagner OEX HD ceramic pads — your standard for ambulance-duty E-450s. Mitchell1 calls 4.0 hrs standard for pad + rotor turn; your last 3 jobs averaged 4.1 hrs. Worldpac shows 6 in stock at your hub.",
    similarJobs: [
      { roId: "4781", vehicle: "Med Trust MT-52", date: "Apr 4, 2026", hours: 4.2 },
      { roId: "4733", vehicle: "Med Trust MT-47", date: "Jan 18, 2026", hours: 4.0 },
      { roId: "4691", vehicle: "Med Trust MT-43", date: "Nov 22, 2025", hours: 4.1 },
    ],
  },
  {
    id: "ai-2",
    findingSeverity: "yellow",
    findingText: "Marker light — driver side rear",
    findingNotes: "LED out, replacement available — 5 min job",
    hasPhoto: true,
    description: "Replace driver-side rear marker light (LED)",
    partNumber: "WHN-VTX-AMB",
    partVendor: "Worldpac",
    partPrice: 42.5,
    laborHours: 0.3,
    laborRate: 148,
    confidence: "high",
    confidencePercent: 92,
    sources: ["shop-history", "worldpac"],
    reasoning:
      "Inspection note matches the Whelen Vertex amber pattern your shop has replaced 4 times this year on similar E-450 ambulances. All sourced from Worldpac at $42.50, average labor 0.3 hrs.",
    similarJobs: [
      { roId: "4812", vehicle: "Med Trust MT-49", date: "May 8, 2026", hours: 0.3 },
      { roId: "4774", vehicle: "Med Trust MT-52", date: "Mar 19, 2026", hours: 0.2 },
    ],
  },
  {
    id: "ai-3",
    findingSeverity: "yellow",
    findingText: "Cabin air filter",
    findingNotes: "Heavily soiled — replace at next visit, $85",
    hasPhoto: true,
    description: "Replace cabin air filter",
    partNumber: "MTC-FP-66",
    partVendor: "OEM Ford",
    partPrice: 28.0,
    laborHours: 0.3,
    laborRate: 148,
    confidence: "high",
    confidencePercent: 98,
    sources: ["mitchell1", "oem"],
    reasoning:
      "Standard Motorcraft FP-66 for 2019 Ford E-450 chassis. Mitchell1: 0.3 hrs labor. OEM in stock at your parts counter.",
  },
  {
    id: "ai-4",
    findingSeverity: "yellow",
    findingText: "Rear ABS wheel sensor — LH",
    findingNotes: "Intermittent fault code C0040, sensor reading drift",
    hasPhoto: false,
    description: "Replace rear ABS wheel sensor (driver side)",
    partNumber: "MTC-ALS-2245",
    partVendor: "Mitchell1",
    partPrice: 185.0,
    laborHours: 1.0,
    laborRate: 148,
    confidence: "medium",
    confidencePercent: 78,
    sources: ["mitchell1", "shop-history", "ai-inferred"],
    reasoning:
      "Inferred from fault code pattern + similar job on MT-52 (Mar 2026, 1.1 hrs). Labor estimate adjusted +20% for ambulance underbody access. Confidence below 90% because this exact ABS module variant has only 1 prior match in your history.",
    similarJobs: [
      { roId: "4774", vehicle: "Med Trust MT-52", date: "Mar 19, 2026", hours: 1.1 },
    ],
  },
];

// Estimated minutes saved if Andy had built this manually (industry avg ~12 min/line)
const MINUTES_PER_LINE_MANUAL = 12;

// ============================================================================
// Modal
// ============================================================================

type Props = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  roId: string;
};

export function AIEstimateBuilderModal({ open, onOpenChange, roId }: Props) {
  const [phase, setPhase] = useState<Phase>("thinking");
  const [thinkingStep, setThinkingStep] = useState(0);
  const [lines, setLines] = useState<ProposedLine[]>(HERO_LINES);
  const [included, setIncluded] = useState<Record<string, boolean>>(
    Object.fromEntries(HERO_LINES.map((l) => [l.id, true])),
  );
  const [expanded, setExpanded] = useState<Record<string, boolean>>({});

  const ro = selectRO(roId);
  const customer = ro ? customers.find((c) => c.id === ro.customerId) : undefined;
  const vehicle = ro ? vehicles.find((v) => v.id === ro.vehicleId) : undefined;

  // Reset state every time the modal opens
  useEffect(() => {
    if (open) {
      setPhase("thinking");
      setThinkingStep(0);
      setLines(HERO_LINES);
      setIncluded(Object.fromEntries(HERO_LINES.map((l) => [l.id, true])));
      setExpanded({});
    }
  }, [open]);

  // Drive the thinking animation — stream the steps over ~1.5s
  useEffect(() => {
    if (!open || phase !== "thinking") return;
    const totalSteps = THINKING_STEPS.length;
    if (thinkingStep < totalSteps) {
      const delay = thinkingStep === 0 ? 200 : 280;
      const t = setTimeout(() => setThinkingStep((s) => s + 1), delay);
      return () => clearTimeout(t);
    }
    // All steps shown — brief pause before revealing the proposals
    const t = setTimeout(() => setPhase("review"), 350);
    return () => clearTimeout(t);
  }, [open, phase, thinkingStep]);

  const selectedLines = lines.filter((l) => included[l.id]);
  const totalAdded = selectedLines.reduce(
    (acc, l) => acc + l.partPrice + l.laborHours * l.laborRate,
    0,
  );
  const totalMinutesSaved = selectedLines.length * MINUTES_PER_LINE_MANUAL;

  const handleApproveAll = () => {
    setIncluded(Object.fromEntries(lines.map((l) => [l.id, true])));
  };
  const handleApproveHighConfidenceOnly = () => {
    setIncluded(
      Object.fromEntries(lines.map((l) => [l.id, l.confidence === "high"])),
    );
  };
  const handleSkipAll = () => {
    setIncluded(Object.fromEntries(lines.map((l) => [l.id, false])));
  };

  const handleConfirm = async () => {
    setPhase("submitting");
    // Brief processing animation
    await new Promise((r) => setTimeout(r, 700));
    applyAIEstimateLines({
      roId,
      lines: selectedLines.map((l) => ({
        description: l.description,
        partNumber: l.partNumber,
        partVendor: l.partVendor,
        partPrice: l.partPrice,
        laborHours: l.laborHours,
        laborRate: l.laborRate,
        total: l.partPrice + l.laborHours * l.laborRate,
      })),
      minutesSaved: totalMinutesSaved,
    });
    setPhase("success");
    // Auto-close after success animation
    setTimeout(() => {
      onOpenChange(false);
      toast.success(`${usdCents.format(totalAdded)} added to RO #${roId}`, {
        description: `${selectedLines.length} lines · ${totalMinutesSaved} min of manual entry saved`,
      });
    }, 1100);
  };

  if (!ro) return null;

  return (
    <Modal
      open={open}
      onOpenChange={(o) => {
        // Don't allow closing during submitting/success — let the auto-close handle it
        if (phase === "submitting" || phase === "success") return;
        onOpenChange(o);
      }}
      title="AI Estimate Builder"
      description={
        phase === "thinking"
          ? "Analyzing inspection findings…"
          : phase === "review"
            ? `RO #${roId} — ${customer?.name} · ${vehicle?.unit}`
            : phase === "submitting"
              ? "Adding lines to estimate…"
              : "Done"
      }
      size="xl"
      footer={
        phase === "review" ? (
          <>
            <div className="mr-auto flex items-center gap-3 text-[11px]">
              <span className="text-muted-foreground">
                {selectedLines.length} of {lines.length} selected
              </span>
              <span className="text-muted-foreground">·</span>
              <span className="inline-flex items-center gap-1 font-semibold text-foreground">
                <TrendingUp className="h-3 w-3" />
                Adds {usdCents.format(totalAdded)}
              </span>
              <span className="text-muted-foreground">·</span>
              <span className="inline-flex items-center gap-1 text-brand-green-soft">
                <Clock className="h-3 w-3" />
                Saves ~{totalMinutesSaved} min
              </span>
            </div>
            <button
              type="button"
              onClick={() => onOpenChange(false)}
              className="rounded-md border border-border bg-background px-3 py-1.5 text-xs font-medium hover:bg-surface"
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={handleConfirm}
              disabled={selectedLines.length === 0}
              className="inline-flex items-center gap-1.5 rounded-md bg-brand-green px-3 py-1.5 text-xs font-semibold text-brand-green-foreground hover:opacity-90 disabled:opacity-40"
            >
              <Check className="h-3 w-3" />
              Add {selectedLines.length} {selectedLines.length === 1 ? "line" : "lines"} to estimate
            </button>
          </>
        ) : null
      }
    >
      {phase === "thinking" && <ThinkingPanel step={thinkingStep} />}

      {phase === "review" && (
        <ReviewPanel
          lines={lines}
          included={included}
          setIncluded={setIncluded}
          expanded={expanded}
          setExpanded={setExpanded}
          totalAdded={totalAdded}
          onApproveAll={handleApproveAll}
          onApproveHighOnly={handleApproveHighConfidenceOnly}
          onSkipAll={handleSkipAll}
        />
      )}

      {phase === "submitting" && (
        <div className="flex h-64 flex-col items-center justify-center gap-3">
          <div className="relative h-12 w-12">
            <div className="absolute inset-0 animate-ping rounded-full bg-brand-green/30" />
            <div className="absolute inset-0 flex items-center justify-center rounded-full bg-brand-green text-brand-green-foreground">
              <Sparkles className="h-5 w-5" />
            </div>
          </div>
          <p className="text-xs text-muted-foreground">Adding lines to estimate…</p>
        </div>
      )}

      {phase === "success" && (
        <div className="flex h-64 flex-col items-center justify-center gap-4">
          <div className="flex h-16 w-16 items-center justify-center rounded-full bg-brand-green text-brand-green-foreground">
            <Check className="h-8 w-8" strokeWidth={3} />
          </div>
          <div className="text-center">
            <div className="text-2xl font-semibold tabular-nums">
              {usdCents.format(totalAdded)}
            </div>
            <div className="text-xs text-muted-foreground">added to estimate</div>
          </div>
          <div className="flex items-center gap-2 rounded-full bg-brand-green-tint px-3 py-1 text-[11px] font-semibold text-brand-green-soft">
            <Clock className="h-3 w-3" />~{totalMinutesSaved} minutes saved
          </div>
        </div>
      )}
    </Modal>
  );
}

// ============================================================================
// Phase 1 — Thinking panel
// ============================================================================

const THINKING_STEPS = [
  "Reading 4 inspection findings",
  "Matching parts across Worldpac, NAPA, OEM",
  "Cross-referencing 47 similar jobs in your shop",
  "Pulling labor times from Mitchell1 + shop history",
  "Calculating markups via Parts Matrix",
];

function ThinkingPanel({ step }: { step: number }) {
  return (
    <div className="min-h-[300px] py-8">
      <div className="mx-auto max-w-md">
        <div className="mb-6 flex items-center justify-center">
          <div className="relative flex h-14 w-14 items-center justify-center rounded-full bg-brand-green-tint">
            <div className="absolute inset-0 animate-ping rounded-full bg-brand-green/20" />
            <Sparkles className="h-6 w-6 text-brand-green-soft" />
          </div>
        </div>
        <ul className="space-y-2.5">
          {THINKING_STEPS.map((label, i) => {
            const done = i < step;
            const current = i === step;
            const pending = i > step;
            return (
              <li
                key={label}
                className={clsx(
                  "flex items-center gap-3 rounded-md border px-3 py-2 text-[12px] transition-all",
                  done && "border-brand-green/30 bg-brand-green-tint",
                  current && "border-brand-green bg-brand-green-tint animate-pulse",
                  pending && "border-border bg-background opacity-50",
                )}
              >
                <span
                  className={clsx(
                    "flex h-5 w-5 shrink-0 items-center justify-center rounded-full",
                    done && "bg-brand-green text-brand-green-foreground",
                    current && "bg-foreground text-background",
                    pending && "bg-surface text-muted-foreground",
                  )}
                >
                  {done ? (
                    <Check className="h-3 w-3" strokeWidth={3} />
                  ) : current ? (
                    <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-background" />
                  ) : null}
                </span>
                <span
                  className={clsx(
                    "font-medium",
                    done && "text-brand-green-soft",
                    current && "text-foreground",
                    pending && "text-muted-foreground",
                  )}
                >
                  {label}
                </span>
              </li>
            );
          })}
        </ul>
      </div>
    </div>
  );
}

// ============================================================================
// Phase 2 — Review panel
// ============================================================================

function ReviewPanel({
  lines,
  included,
  setIncluded,
  expanded,
  setExpanded,
  totalAdded,
  onApproveAll,
  onApproveHighOnly,
  onSkipAll,
}: {
  lines: ProposedLine[];
  included: Record<string, boolean>;
  setIncluded: React.Dispatch<React.SetStateAction<Record<string, boolean>>>;
  expanded: Record<string, boolean>;
  setExpanded: React.Dispatch<React.SetStateAction<Record<string, boolean>>>;
  totalAdded: number;
  onApproveAll: () => void;
  onApproveHighOnly: () => void;
  onSkipAll: () => void;
}) {
  return (
    <div className="space-y-4">
      {/* Header summary */}
      <div className="rounded-lg border border-brand-green/30 bg-brand-green-tint p-4">
        <div className="flex items-start gap-3">
          <Sparkles className="mt-0.5 h-5 w-5 shrink-0 text-brand-green-soft" />
          <div className="min-w-0 flex-1">
            <h3 className="text-sm font-semibold text-brand-green-soft">
              Found {lines.length} unestimated findings — proposed{" "}
              {usdCents.format(totalAdded)} in additional work
            </h3>
            <p className="mt-1 text-[11px] text-brand-green-soft/80">
              Each line is grounded in your shop's history, Mitchell1 labor guides,
              and live vendor catalogs. Review proposed lines; toggle Include to
              add or skip per line.
            </p>
          </div>
        </div>
        <div className="mt-3 flex flex-wrap items-center gap-1.5">
          <button
            type="button"
            onClick={onApproveAll}
            className="rounded-full bg-brand-green px-2.5 py-1 text-[11px] font-semibold text-brand-green-foreground hover:opacity-90"
          >
            Approve all
          </button>
          <button
            type="button"
            onClick={onApproveHighOnly}
            className="rounded-full border border-brand-green/40 bg-background px-2.5 py-1 text-[11px] font-semibold text-brand-green-soft hover:bg-brand-green/10"
          >
            Approve high-confidence only
          </button>
          <button
            type="button"
            onClick={onSkipAll}
            className="rounded-full border border-border bg-background px-2.5 py-1 text-[11px] font-semibold text-muted-foreground hover:bg-surface"
          >
            Skip all
          </button>
        </div>
      </div>

      {/* Lines */}
      <div className="space-y-3">
        {lines.map((line) => (
          <ProposedLineCard
            key={line.id}
            line={line}
            included={!!included[line.id]}
            onToggle={() =>
              setIncluded((p) => ({ ...p, [line.id]: !p[line.id] }))
            }
            isExpanded={!!expanded[line.id]}
            onToggleExpand={() =>
              setExpanded((p) => ({ ...p, [line.id]: !p[line.id] }))
            }
          />
        ))}
      </div>
    </div>
  );
}

// ============================================================================
// ProposedLineCard
// ============================================================================

function ProposedLineCard({
  line,
  included,
  onToggle,
  isExpanded,
  onToggleExpand,
}: {
  line: ProposedLine;
  included: boolean;
  onToggle: () => void;
  isExpanded: boolean;
  onToggleExpand: () => void;
}) {
  const total = line.partPrice + line.laborHours * line.laborRate;
  return (
    <div
      className={clsx(
        "overflow-hidden rounded-lg border bg-background transition-all",
        included
          ? "border-border shadow-sm"
          : "border-border opacity-50",
      )}
    >
      <div className="grid grid-cols-[1fr_24px_1.4fr_auto] items-stretch">
        {/* LEFT — Inspection finding */}
        <div className="border-r border-border bg-surface/40 p-4">
          <div className="mb-2 flex items-center gap-1.5">
            <span
              className={clsx(
                "rounded-full px-1.5 py-0.5 text-[9px] font-bold uppercase tracking-wider",
                line.findingSeverity === "red"
                  ? "bg-destructive text-destructive-foreground"
                  : "bg-accent text-accent-foreground",
              )}
            >
              {line.findingSeverity === "red" ? "Red" : "Yellow"}
            </span>
            {line.hasPhoto && (
              <span className="inline-flex items-center gap-1 rounded-full bg-foreground/10 px-1.5 py-0.5 text-[9px] font-semibold text-foreground/60">
                <Camera className="h-2.5 w-2.5" />
                Photo
              </span>
            )}
            <span className="text-[10px] uppercase tracking-wider text-muted-foreground">
              Inspection finding
            </span>
          </div>
          {line.hasPhoto && (
            <div className="mb-2 flex h-16 items-center justify-center rounded-md border border-border bg-background">
              <Camera className="h-5 w-5 text-muted-foreground/40" />
            </div>
          )}
          <p className="text-xs font-semibold leading-snug">{line.findingText}</p>
          {line.findingNotes && (
            <p className="mt-1 text-[10px] italic text-muted-foreground">
              "{line.findingNotes}"
            </p>
          )}
        </div>

        {/* Arrow */}
        <div className="flex items-center justify-center bg-surface/20">
          <ArrowRight className="h-4 w-4 text-muted-foreground/60" />
        </div>

        {/* RIGHT — Proposed line */}
        <div className="p-4">
          <div className="mb-2 flex items-center justify-between gap-2">
            <div className="flex items-center gap-1.5">
              <Sparkles className="h-3 w-3 text-brand-green-soft" />
              <span className="text-[10px] uppercase tracking-wider text-muted-foreground">
                AI-proposed line
              </span>
            </div>
            <ConfidencePill
              confidence={line.confidence}
              percent={line.confidencePercent}
            />
          </div>

          <div className="text-sm font-semibold">{line.description}</div>

          <div className="mt-2 grid grid-cols-2 gap-3 text-[11px]">
            <div>
              <div className="flex items-center gap-1 text-muted-foreground">
                <Package className="h-2.5 w-2.5" />
                <span className="uppercase tracking-wider">Part</span>
              </div>
              <div className="mt-0.5 font-medium">
                <span className="font-mono text-[10px]">{line.partNumber}</span>
                <span className="ml-1.5 text-muted-foreground">·</span>
                <span className="ml-1.5 text-muted-foreground">
                  {line.partVendor}
                </span>
              </div>
              <div className="mt-0.5 font-semibold tabular-nums">
                {usdCents.format(line.partPrice)}
              </div>
            </div>
            <div>
              <div className="flex items-center gap-1 text-muted-foreground">
                <Wrench className="h-2.5 w-2.5" />
                <span className="uppercase tracking-wider">Labor</span>
              </div>
              <div className="mt-0.5 font-medium tabular-nums">
                {line.laborHours.toFixed(1)} hrs @ ${line.laborRate}/hr
              </div>
              <div className="mt-0.5 font-semibold tabular-nums">
                {usdCents.format(line.laborHours * line.laborRate)}
              </div>
            </div>
          </div>

          {/* Line total */}
          <div className="mt-3 flex items-center justify-between border-t border-border pt-2">
            <span className="text-[10px] uppercase tracking-wider text-muted-foreground">
              Line total
            </span>
            <span className="text-base font-bold tabular-nums">
              {usdCents.format(total)}
            </span>
          </div>

          {/* Sources */}
          <div className="mt-2 flex flex-wrap items-center gap-1">
            {line.sources.map((s) => (
              <SourcePill key={s} source={s} />
            ))}
          </div>

          {/* Why? */}
          <button
            type="button"
            onClick={onToggleExpand}
            className="mt-2 inline-flex items-center gap-1 text-[10px] font-semibold text-muted-foreground transition-colors hover:text-foreground"
          >
            {isExpanded ? (
              <ChevronUp className="h-3 w-3" />
            ) : (
              <ChevronDown className="h-3 w-3" />
            )}
            Why this proposal?
          </button>
          {isExpanded && (
            <div className="mt-2 space-y-2 rounded-md border border-border bg-surface/30 p-2.5">
              <p className="text-[11px] leading-relaxed text-foreground/85">
                {line.reasoning}
              </p>
              {line.similarJobs && line.similarJobs.length > 0 && (
                <div className="border-t border-border pt-2">
                  <div className="text-[9px] font-semibold uppercase tracking-wider text-muted-foreground">
                    Similar jobs in your shop
                  </div>
                  <ul className="mt-1 space-y-0.5">
                    {line.similarJobs.map((j) => (
                      <li
                        key={j.roId}
                        className="flex items-center justify-between text-[10px]"
                      >
                        <span>
                          <span className="font-mono text-muted-foreground">
                            RO #{j.roId}
                          </span>{" "}
                          · {j.vehicle} · {j.date}
                        </span>
                        <span className="font-semibold tabular-nums">
                          {j.hours.toFixed(1)} hrs
                        </span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Far right — include toggle (spans 1 column visually, attached to right side) */}
        <div className="flex items-center border-l border-border bg-surface/40 px-3">
          <button
            type="button"
            onClick={onToggle}
            title={included ? "Skip this line" : "Include this line"}
            className={clsx(
              "flex h-9 w-9 items-center justify-center rounded-full transition-colors",
              included
                ? "bg-brand-green text-brand-green-foreground hover:opacity-90"
                : "border border-border bg-background text-muted-foreground hover:border-foreground/40",
            )}
          >
            {included ? (
              <Check className="h-4 w-4" strokeWidth={3} />
            ) : (
              <X className="h-4 w-4" />
            )}
          </button>
        </div>
      </div>
    </div>
  );
}

// ============================================================================
// ConfidencePill
// ============================================================================

function ConfidencePill({
  confidence,
  percent,
}: {
  confidence: Confidence;
  percent: number;
}) {
  const styles: Record<Confidence, string> = {
    high: "bg-brand-green-tint text-brand-green-soft border-brand-green/40",
    medium: "bg-accent/30 text-[#991B1B] border-accent/60",
    low: "bg-destructive/10 text-destructive border-destructive/40",
  };
  const label: Record<Confidence, string> = {
    high: "High",
    medium: "Medium",
    low: "Low",
  };
  return (
    <span
      className={clsx(
        "inline-flex items-center gap-1 rounded-full border px-1.5 py-0.5 text-[9px] font-bold",
        styles[confidence],
      )}
    >
      <Zap className="h-2.5 w-2.5" />
      <span className="uppercase tracking-wider">{label[confidence]}</span>
      <span className="tabular-nums opacity-80">{percent}%</span>
    </span>
  );
}

// ============================================================================
// SourcePill
// ============================================================================

const SOURCE_LABELS: Record<Source, string> = {
  "shop-history": "Shop History",
  mitchell1: "Mitchell1",
  worldpac: "Worldpac",
  oem: "OEM",
  "ai-inferred": "AI Inferred",
};

const SOURCE_STYLES: Record<Source, string> = {
  "shop-history": "bg-foreground text-background",
  mitchell1: "bg-[#3730A3] text-white",
  worldpac: "bg-[#1E40AF] text-white",
  oem: "bg-success text-success-foreground",
  "ai-inferred": "bg-accent text-accent-foreground",
};

function SourcePill({ source }: { source: Source }) {
  return (
    <span
      className={clsx(
        "inline-flex items-center rounded px-1.5 py-0.5 text-[9px] font-bold uppercase tracking-wider",
        SOURCE_STYLES[source],
      )}
    >
      {SOURCE_LABELS[source]}
    </span>
  );
}

// silence unused-import warning for AlertTriangle while keeping it available for edge cases
const _AlertTriangle = AlertTriangle;
void _AlertTriangle;
